

export const GET_ALL_PRODUCT_REQUEST = 'GET_ALL_PRODUCT_REQUEST'
export const GET_ALL_PRODUCT_SUCCESS = 'GET_ALL_PRODUCT_SUCCESS'
export const GET_ALL_PRODUCT_FAILED = 'GET_ALL_PRODUCT_FAILED'

export const GET_SINGLE_PRODUCT_REQUEST = 'GET_SINGLE_PRODUCT_REQUEST'
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS'
export const GET_SINGLE_PRODUCT_FAILED = 'GET_SINGLE_PRODUCT_FAILED'

export const ADD_TO_WISHLIST_REQUEST = 'ADD_TO_WISHLIST_REQUEST'
export const ADD_TO_WISHLIST_SUCCESS = 'ADD_TO_WISHLIST_SUCCESS'
export const ADD_TO_WISHLIST_FAILED = 'ADD_TO_WISHLIST_FAILED'

export const GET_WISHLIST_REQUEST = 'GET_WISHLIST_REQUEST'
export const GET_WISHLIST_SUCCESS = 'GET_WISHLIST_SUCCESS'
export const GET_WISHLIST_FAILED = 'GET_WISHLIST_FAILED'

export const CHECK_IF_WISHLIST_REQUEST = 'CHECK_IF_WISHLIST_REQUEST'
export const CHECK_IF_WISHLIST_SUCCESS = 'CHECK_IF_WISHLIST_SUCCESS'
export const CHECK_IF_WISHLIST_FAILED = 'CHECK_IF_WISHLIST_FAILED'